apiVersion: v1
kind: PersistentVolume
metadata:
  name: rwx02
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 3.23.29.220
    path: /data/2